
services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./app_data:/data/db


  bot:
    container_name: rlt_test_bot
    build:
      dockerfile: ./Dockerfile
    command:
      - "python"
      - "main.py"
    restart: on-failure
    volumes:
      - ./app_data/logs/bot:/bot/logs
    env_file:
      - .env
    links:
      - mongo
    depends_on:
      mongo:
        condition: service_started

